beinSport1       : 46
beinSport2       : 47
BFM              : 103
RMC              : 98
Comedie          : 42
DiscoveryScience : 60
Canal+           : 4
France2          : 2
France3          : 3
France4          : 544
RTL9             : 45
AB1              : 45
TEVA             : 45
NT1              : 45
GameOne          : 45
J-One            : 45
